"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import datetime
import boto3
import os

ssm=boto3.client('ssm',region_name=os.getenv('AWS_REGION','ap-south-1'))

def get_ssm_param(name):
  return ssm.get_parameter(Name=name,WithDecryption=True)['Parameter']['Value']

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!^kgc_w=so@79!s)v!o&#$^2jlmpl4rr7bdug&2xa=a2$nkvwu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['13.234.124.118','13.233.78.207','localhost','127.0.0.1']


CORS_ALLOW_CREDENTIALS = True
CORS_URLS_REGEX = r"^/(user)/.*"

if DEBUG:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173", 
        "http://127.0.0.1:5173",
    ]
else:
    CORS_ALLOWED_ORIGINS = [
        # Add your production frontend URLs here
           "http://localhost:5173",
    ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'inventory',
    'marketing',
    'api',
    'rest_framework.authtoken', 
    'rest_framework_simplejwt', 
    "corsheaders",
    'rest_framework', 
   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': get_ssm_param('/Ecommerce/db_name'),  # Database name
#         'USER': 'postgres',  # MySQL username (e.g., 'root')
#         'PASSWORD': get_ssm_param('/Ecommerce/db_passowrd'),  # MySQL password
#         'HOST':get_ssm_param('/Ecommerce/db_DNS'),  # Or '127.0.0.1' or your MySQL server IP
#         'PORT': '5432',  # Default MySQL port
#         'OPTIONS': {
#          'connect_timeout': 10,
#         },
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
import os
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK={
  'DEFAULT_AUTHENTICATION_CLASSES':[
      'rest_framework.authentication.SessionAuthentication',
          "rest_framework_simplejwt.authentication.JWTAuthentication",
  ],
    "DEFAULT_PERMISSION_CLASSES":[
                   "rest_framework.permissions.IsAuthenticatedOrReadOnly"
  ],
  
}

SIMPLE_JWT={
  'AUTH_HEADER_TYPES':["Bearer"],
  "ACCESS_TOKEN_LIFETIME":datetime.timedelta(minutes=15) ,
  "REFRESH_TOKEN_LIFETIME":datetime.timedelta(minutes=45)


}

AWS_ACCESS_KEY_ID = get_ssm_param('/Ecommerce/aws_access_key')
AWS_SECRET_ACCESS_KEY = get_ssm_param('/Ecommerce/aws_secret_access_key')
AWS_S3_REGION_NAME = get_ssm_param('/Ecommerce/aws_s3_region_name')
AWS_STORAGE_BUCKET_NAME = get_ssm_param('/StudyBud/s3_bucket_name')
AWS_SNS_ARN=get_ssm_param('/StudyBud/sns_arn')