"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import datetime
import boto3
import os


ssm=boto3.client('ssm',region_name=os.getenv('AWS_REGION','ap-south-1'))

def get_ssm_param(name):
  return ssm.get_parameter(Name=name,WithDecryption=True)['Parameter']['Value']

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!^kgc_w=so@79!s)v!o&#$^2jlmpl4rr7bdug&2xa=a2$nkvwu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['13.234.124.118','13.233.78.207','localhost','127.0.0.1']


# In your DEBUG section, update:
if DEBUG:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173", 
        "http://127.0.0.1:5173",
    ]
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        # Add your production frontend URLs here when you deploy frontend
    ]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://13.234.124.118",  # Add your backend server
    "http://13.233.78.207",   # Add your other backend server
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Add this to allow all methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Add this to allow headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'mcp_server',
]

INSTALLED_APPS = [
    "daphne",      
    "channels",
    "chat",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'inventory',
    'marketing',
    'api',
    'rest_framework.authtoken', 
    'rest_framework_simplejwt', 
    "corsheaders",
    'rest_framework', 
   
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'ecommerce.wsgi.application'
ASGI_APPLICATION = "ecommerce.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': get_ssm_param('/Ecommerce/db_name'),  # Database name
#         'USER': 'postgres',  # MySQL username (e.g., 'root')
#         'PASSWORD': get_ssm_param('/Ecommerce/db_passowrd'),  # MySQL password
#         'HOST':get_ssm_param('/Ecommerce/db_DNS'),  # Or '127.0.0.1' or your MySQL server IP
#         'PORT': '5432',  # Default MySQL port
#         'OPTIONS': {
#          'connect_timeout': 10,
#         },
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
import os
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK={
  'DEFAULT_AUTHENTICATION_CLASSES':[
      'api.authentication.CookieJWTAuthentication',  # so we built custom auth
          "rest_framework_simplejwt.authentication.JWTAuthentication", # it reads token from  'Authorization: Bearer <token>' but we are using cookies
                    'rest_framework.authentication.SessionAuthentication',

  ],
    "DEFAULT_PERMISSION_CLASSES":[
                   "rest_framework.permissions.IsAuthenticatedOrReadOnly"
  ],
    'COERCE_DECIMAL_TO_STRING': False,   # if we want decimal values to be string Make it "True"  decimal on frontend caues rounding errors so string is better(True)
  "DEFAULT_PAGINATION_CLASS":"rest_framework.pagination.PageNumberPagination","PAGE_SIZE":2 
  
}

SIMPLE_JWT={
  'AUTH_HEADER_TYPES':["Bearer"],
  "ACCESS_TOKEN_LIFETIME":datetime.timedelta(minutes=45) ,
  "REFRESH_TOKEN_LIFETIME":datetime.timedelta(days=15)


}

AWS_ACCESS_KEY_ID = get_ssm_param('/Ecommerce/aws_access_key')
AWS_SECRET_ACCESS_KEY = get_ssm_param('/Ecommerce/aws_secret_access_key')
AWS_S3_REGION_NAME = get_ssm_param('/Ecommerce/aws_s3_region_name')
AWS_STORAGE_BUCKET_NAME = get_ssm_param('/StudyBud/s3_bucket_name')
AWS_SNS_ARN=get_ssm_param('/StudyBud/sns_arn')

DJANGO_MCP_GLOBAL_SERVER_CONFIG = {
    "name": "Ecommerce MCP Server",
    "instructions": "Read-only MCP tools for ecommerce users, carts, and orders.",
}


# ── Anthropic / MCP proxy ────────────────────────────────────────────────────
# Replace these values with your real keys before running.
# In production, load them from SSM / env vars just like the AWS keys above.
ANTHROPIC_API_KEY = get_ssm_param('/Ecommerce/aws_anthropic_ai_api_key')   # TODO: move to SSM
MCP_SERVER_URL    =  "https://lid-canon-sedative.ngrok-free.dev"    # TODO: public URL for prod
# ────────────────────────────────────────────────────────────────────────────


# settings.py
# REST_FRAMEWORK = {  # if we want decimal values to be string Make it "True"  decimal on frontend caues rounding errors so string is better(True)
#     'COERCE_DECIMAL_TO_STRING': False,
# }

AUTH_USER_MODEL = 'api.User'

CORS_ALLOW_CREDENTIALS = True


SESSION_COOKIE_SAMESITE = 'Lax'       # 'None' only if cross-site + HTTPS
SESSION_COOKIE_SECURE   = False        # True in production (HTTPS only)

CSRF_COOKIE_SAMESITE    = 'Lax'
CSRF_COOKIE_SECURE      = False
CSRF_COOKIE_HTTPONLY    = False    

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379,0)],
        },
    },
}

CELERY_BROKER_URL = 'redis://localhost:6379/1'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/2'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'

# Optional but recommended:
CELERY_TASK_TRACK_STARTED = True      # marks task as STARTED (not just PENDING)
CELERY_TASK_TIME_LIMIT = 30 * 60      # hard kill after 30 min
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60 # SoftTimeLimitExceeded raised at 25 min

# For periodic tasks (requires django-celery-beat):
# INSTALLED_APPS += ['django_celery_beat']  something like inventory sync or any db sync we can use this

RAZORPAY_KEY_ID =  get_ssm_param('/Ecommerce/aws_razorpay_id')
RAZORPAY_KEY_SECRET = get_ssm_param('/Ecommerce/aws_razorpay_key_secret')